#pragma once

// If you define a constant, the corresponding test should fail to compile.

//#define MAP_COMPARE_COPY_CONSTRUCTIBLE_FAIL
//#define MULTIMAP_COMPARE_COPY_CONSTRUCTIBLE_FAIL
//#define MULTISET_COMPARE_COPY_CONSTRUCTIBLE_FAIL
//#define SET_COMPARE_COPY_CONSTRUCTIBLE_FAIL

//#define MAP_COUNT_FAIL1
//#define MAP_COUNT_FAIL2
//#define MAP_COUNT_FAIL3
//#define MAP_FIND_FAIL1
//#define MAP_FIND_FAIL2
//#define MAP_FIND_FAIL3
//#define MAP_ERANGE_FAIL1
//#define MAP_ERANGE_FAIL2
//#define MAP_ERANGE_FAIL3
//#define MAP_LBOUND_FAIL1
//#define MAP_LBOUND_FAIL2
//#define MAP_LBOUND_FAIL3
//#define MAP_UBOUND_FAIL1
//#define MAP_UBOUND_FAIL2
//#define MAP_UBOUND_FAIL3

//#define MULTIMAP_COUNT_FAIL1
//#define MULTIMAP_COUNT_FAIL2
//#define MULTIMAP_COUNT_FAIL3
//#define MULTIMAP_FIND_FAIL1
//#define MULTIMAP_FIND_FAIL2
//#define MULTIMAP_FIND_FAIL3
//#define MULTIMAP_ERANGE_FAIL1
//#define MULTIMAP_ERANGE_FAIL2
//#define MULTIMAP_ERANGE_FAIL3
//#define MULTIMAP_LBOUND_FAIL1
//#define MULTIMAP_LBOUND_FAIL2
//#define MULTIMAP_LBOUND_FAIL3
//#define MULTIMAP_UBOUND_FAIL1
//#define MULTIMAP_UBOUND_FAIL2
//#define MULTIMAP_UBOUND_FAIL3

// only if ALLOW_ALLOCATOR_MISMATCH is not defined:

//#define MAP_ALLOCATOR_MISMATCH_FAIL
//#define MULTIMAP_ALLOCATOR_MISMATCH_FAIL
//#define MULTISET_ALLOCATOR_MISMATCH_FAIL
//#define SET_ALLOCATOR_MISMATCH_FAIL